// Generated by CoffeeScript 1.11.1

/**
 * The default SyntaxError class doesn't accept fileName or lineNumber args.
 * Also, being able to pass in the context (text that threw the error) is nice.
 */
var EditorConfigError,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

EditorConfigError = (function(superClass) {
  extend(EditorConfigError, superClass);

  function EditorConfigError(message, fileName, lineNumber, context1) {
    this.message = message;
    this.fileName = fileName;
    this.lineNumber = lineNumber;
    this.context = context1;
    this.toString = bind(this.toString, this);
  }

  EditorConfigError.prototype.toString = function() {
    var text;
    text = this.fileName;
    if (this.lineNumber != null) {
      text += ":" + this.lineNumber;
    }
    if (this.context != null) {
      text += "\n" + context;
    }
    return text += "\nEditorConfigError: " + this.message;
  };

  return EditorConfigError;

})(Error);

module.exports = EditorConfigError;
