// Generated by CoffeeScript 1.11.1
var editorconfig;

editorconfig = require('editorconfig').parse;


/**
 * Wrapper for the editorconfig function - converts `indent_style` and
   `indent_size` into `indent_char`
 */

module.exports = function(filepath) {
  return editorconfig(filepath).then(function(properties) {
    properties['indent_char'] = ('tab' === properties['indent_size'] || 'tab' === properties['indent_style'] ? '\t' : !isNaN(properties['indent_size']) ? Array(properties['indent_size'] + 1).join(' ') : properties['indent_style'] === 'space' ? '  ' : void 0);
    delete properties['indent_style'];
    delete properties['indent_size'];
    return properties;
  });
};
